# Generated by Django 4.1.5 on 2023-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Map", max_length=100)),
                ("location_latitude", models.FloatField(default=37.8283)),
                ("location_longitude", models.FloatField(default=-95.5795)),
                ("zoom", models.FloatField(default=4.5)),
                ("tiles", models.CharField(default="Stamen Terrain", max_length=255)),
                (
                    "attr",
                    models.CharField(
                        default='Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.',
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
