# Generated by Django 4.1.5 on 2023-01-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mapthat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("popup", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("lightblue", "Lightblue"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("cadetblue", "Cadetblue"),
                            ("darkpurple", "Darkpurple"),
                            ("red", "Red"),
                            ("beige", "Beige"),
                            ("black", "Black"),
                            ("darkred", "Darkred"),
                            ("darkgreen", "Darkgreen"),
                            ("gray", "Gray"),
                            ("lightgray", "Lightgray"),
                            ("orange", "Orange"),
                            ("lightred", "Lightred"),
                            ("purple", "Purple"),
                            ("darkblue", "Darkblue"),
                            ("lightgreen", "Lightgreen"),
                            ("white", "White"),
                        ],
                        default="red",
                        max_length=100,
                    ),
                ),
                ("tooltip", models.CharField(default=None, max_length=100)),
                (
                    "map",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mapthat.map",
                    ),
                ),
            ],
        ),
    ]
