# Generated by Django 4.1.5 on 2023-01-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapthat", "0002_marker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("lightblue", "Lightblue"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                            ("cadetblue", "Cadetblue"),
                            ("darkpurple", "Darkpurple"),
                            ("red", "Red"),
                            ("beige", "Beige"),
                            ("black", "Black"),
                            ("darkred", "Darkred"),
                            ("darkgreen", "Darkgreen"),
                            ("gray", "Gray"),
                            ("lightgray", "Lightgray"),
                            ("orange", "Orange"),
                            ("lightred", "Lightred"),
                            ("purple", "Purple"),
                            ("darkblue", "Darkblue"),
                            ("lightgreen", "Lightgreen"),
                            ("white", "White"),
                        ],
                        default="red",
                        max_length=100,
                    ),
                ),
                ("icon_color", models.CharField(default="white", max_length=100)),
                ("icon", models.CharField(default="fa-bank", max_length=100)),
                ("angle", models.IntegerField(default=0)),
                ("prefix", models.CharField(default="fa", max_length=100)),
            ],
        ),
    ]
